---
title: "Assignment 2"
author: Emmanuel Assenso Antwi
date: 2022
output: word_document
---

```{r, echo = True}
#The data measured alcohol consumption in different countries around the world. The product used for the studies was beer, spirits and wine. The kind of research questions the data could be answering is Which country consumed the most alcohol?, which countries abstained from alcohol. The data was sourced from W.H.O. W.H.O  used government records as well as statistics from the alcohol industry and the United Nation’s Food and Agriculture Organization database. The data was presented in liters of pure alcohol but for easy comparison, the researcher converted those numbers into standard serving sizes. The results show how many glasses of wine, cans of beer and shots of spirits were drunk per person in each country in 2010. The file is a flat file ie csv file. 
```

```{r setup, include = true}
library(dplyr)
library(knitr)
library(dplyr)
```

```{r get data, include = TRUE}
#url <- "https://raw.githubusercontent.com/fivethirtyeight/data/master/alcohol-consumption/drinks.csv"
Alchohol <- read.csv(url)
glimpse(Alchohol)
```

```{r clean data, include = TRUE}
abstain <- Alchohol %>%
  filter(total_litres_of_pure_alcohol <= 0.1)
summary(abstain)
```
 


``` #This next chunk is inline code. 
```
This dataframe has `r nrow(dataset)` rows and `r ncol(dataset)` columns. The names of the columns and a brief description of each are in the table below:

```{r, echo = True}
text_tbl <- data.frame(
Names = c("country","total_litres_of_pure_alcoho"), 
Description = c("names of countries", "total litres of pure alcohol consumed"))
text_tbl
```

```{r, echo = True}
data_pick3 <- select(Alcohol, beer_servings, spirit_servings, wine_servings).
Summarytable<-summary(data_pick3)
```
